# TL;DR: YOU SHOULD DELETE THIS FILE
#
# This file was generated by Cucumber-Rails and is only here to get you a head start
# These step definitions are thin wrappers around the Capybara/Webrat API that lets you
# visit pages, interact with widgets and make assertions about page content.
#
# If you use these step definitions as basis for your features you will quickly end up
# with features that are:
#
# * Hard to maintain
# * Verbose to read
#
# A much better approach is to write your own higher level step definitions, following
# the advice in the following blog posts:
#
# * http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html
# * http://dannorth.net/2011/01/31/whose-domain-is-it-anyway/
# * http://elabs.se/blog/15-you-re-cuking-it-wrong
#

require 'fakeweb'
require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "selectors"))

module WithinHelpers
  def with_scope(locator)
    locator ? within(*selector_for(locator)) { yield } : yield
  end
end
World(WithinHelpers)

# Single-line step scoper
When /^(.*) within (.*[^:])$/ do |step, parent|
  with_scope(parent) { When step }
end

# Multi-line step scoper
When /^(.*) within (.*[^:]):$/ do |step, parent, table_or_string|
  with_scope(parent) { When "#{step}:", table_or_string }
end

Given /^(?:|I )am on (.+)$/ do |page_name|
  FakeWeb.register_uri(:any, %r[http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch*], 
    :body => %Q{
<PubmedArticleSet>
<PubmedArticle>
    <MedlineCitation Owner="NLM" Status="In-Data-Review">
        <PMID Version="1">23197953</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print-Electronic">
            <Journal>
                <ISSN IssnType="Electronic">1664-5510</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <Volume>2</Volume>
                    <Issue>1</Issue>
                    <PubDate>
                        <Year>2012</Year>
                        <Month>Jan</Month>
                    </PubDate>
                </JournalIssue>
                <Title>Case reports in nephrology and urology</Title>
                <ISOAbbreviation>Case Rep Nephrol Urol</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Posterior Reversible Encephalopathy Syndrome during Recovery from Acute Kidney Injury after Hepatitis A Infection.</ArticleTitle>
            <Pagination>
                <MedlinePgn>33-7</MedlinePgn>
            </Pagination>
            <ELocationID EIdType="doi" ValidYN="Y">10.1159/000339253</ELocationID>
            <Abstract>
                <AbstractText>The patient was a 25-year-old healthy male who experienced fever, chills, and abdominal pain for 5 days prior to the hospital visit. He was diagnosed with acute hepatitis A, and at admission he presented with anuric acute kidney injury and hepatic encephalopathy. He received continuous renal replacement therapy followed by intermittent regular hemodialysis. His urine output increased to 1,610 ml/day after 31 days. On day 32, he suddenly developed a headache and visual disturbance and experienced three short convulsions, which were followed by postictal confusion and high fever. T2 and FLAIR MRI images of the brain revealed hyperintense signal alterations in bilateral subcortical regions of the temporoparietal and occipital lobes, consistent with posterior reversible encephalopathy syndrome. His mental status was fully recovered after 7 h of conservative treatment, including antihypertensive therapy. On hospital day 56, the renal function of the patient had recovered, and he was discharged without neurologic sequelae.</AbstractText>
            </Abstract>
            <Affiliation>Division of Nephrology, Department of Medicine, Samsung Medical Center, Sungkyunkwan University School of Medicine, Seoul, Korea.</Affiliation>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Kim</LastName>
                    <ForeName>Soo Min</ForeName>
                    <Initials>SM</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Choi</LastName>
                    <ForeName>Heejung</ForeName>
                    <Initials>H</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Kim</LastName>
                    <ForeName>Yoonjung</ForeName>
                    <Initials>Y</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Shin</LastName>
                    <ForeName>Junam</ForeName>
                    <Initials>J</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Jang</LastName>
                    <ForeName>Hye Ryoun</ForeName>
                    <Initials>HR</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Lee</LastName>
                    <ForeName>Jung Eun</ForeName>
                    <Initials>JE</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Huh</LastName>
                    <ForeName>Wooseong</ForeName>
                    <Initials>W</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Kim</LastName>
                    <ForeName>Dae Joong</ForeName>
                    <Initials>DJ</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Oh</LastName>
                    <ForeName>Ha Young</ForeName>
                    <Initials>HY</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Kim</LastName>
                    <ForeName>Yoon-Goo</ForeName>
                    <Initials>YG</Initials>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType>Journal Article</PublicationType>
            </PublicationTypeList>
            <ArticleDate DateType="Electronic">
                <Year>2012</Year>
                <Month>05</Month>
                <Day>24</Day>
            </ArticleDate>
        </Article>
        <MedlineJournalInfo>
            <Country>Switzerland</Country>
            <MedlineTA>Case Rep Nephrol Urol</MedlineTA>
            <NlmUniqueID>101591817</NlmUniqueID>
            <ISSNLinking>1664-5510</ISSNLinking>
        </MedlineJournalInfo>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="epublish">
                <Year>2012</Year>
                <Month>5</Month>
                <Day>24</Day>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>ppublish</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="doi">10.1159/000339253</ArticleId>
            <ArticleId IdType="pii">cru-0002-0033</ArticleId>
            <ArticleId IdType="pubmed">23197953</ArticleId>
            <ArticleId IdType="pmc">PMC3482082</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Status="Publisher" Owner="NLM">
        <PMID Version="1">23197746</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print-Electronic">
            <Journal>
                <ISSN IssnType="Electronic">1526-632X</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <PubDate>
                        <Year>2012</Year>
                        <Month>Nov</Month>
                        <Day>28</Day>
                    </PubDate>
                </JournalIssue>
                <Title>Neurology</Title>
                <ISOAbbreviation>Neurology</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Long-term treatment of a patient with severe restless legs syndrome using intrathecal morphine.</ArticleTitle>
            <Pagination>
                <MedlinePgn/>
            </Pagination>
            <Affiliation>From the Interdisciplinary Pain Center (M.H., H.K.), University Medical Centre Freiburg, Freiburg; Pain Medicine Centers (M.H.), Algesiologikum, Munich; and Neurology and Headache Center Munchner Freiheit (H.K.), Munich, Germany.</Affiliation>
            <AuthorList>
                <Author>
                    <LastName>Hornyak</LastName>
                    <ForeName>Magdolna</ForeName>
                    <Initials>M</Initials>
                </Author>
                <Author>
                    <LastName>Kaube</LastName>
                    <ForeName>Holger</ForeName>
                    <Initials>H</Initials>
                </Author>
            </AuthorList>
            <Language>ENG</Language>
            <PublicationTypeList>
                <PublicationType>JOURNAL ARTICLE</PublicationType>
            </PublicationTypeList>
            <ArticleDate DateType="Electronic">
                <Year>2012</Year>
                <Month>11</Month>
                <Day>28</Day>
            </ArticleDate>
        </Article>
        <MedlineJournalInfo>
            <MedlineTA>Neurology</MedlineTA>
            <NlmUniqueID>0401060</NlmUniqueID>
            <ISSNLinking>0028-3878</ISSNLinking>
        </MedlineJournalInfo>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>aheadofprint</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">WNL.0b013e318278b5e7</ArticleId>
            <ArticleId IdType="doi">10.1212/WNL.0b013e318278b5e7</ArticleId>
            <ArticleId IdType="pubmed">23197746</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Status="Publisher" Owner="NLM">
        <PMID Version="1">23197350</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print-Electronic">
            <Journal>
                <ISSN IssnType="Electronic">1468-2982</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <PubDate>
                        <Year>2012</Year>
                        <Month>Nov</Month>
                        <Day>29</Day>
                    </PubDate>
                </JournalIssue>
                <Title>Cephalalgia : an international journal of headache</Title>
                <ISOAbbreviation>Cephalalgia</ISOAbbreviation>
            </Journal>
            <ArticleTitle>A role for steroids in treating medication overuse headache?</ArticleTitle>
            <Pagination>
                <MedlinePgn/>
            </Pagination>
            <Affiliation>Mayo Clinic, Scottsdale, AZ, USA.</Affiliation>
            <AuthorList>
                <Author>
                    <LastName>Halker</LastName>
                    <ForeName>Rashmi B</ForeName>
                    <Initials>RB</Initials>
                </Author>
                <Author>
                    <LastName>Dilli</LastName>
                    <ForeName>Esma</ForeName>
                    <Initials>E</Initials>
                </Author>
            </AuthorList>
            <Language>ENG</Language>
            <PublicationTypeList>
                <PublicationType>JOURNAL ARTICLE</PublicationType>
            </PublicationTypeList>
            <ArticleDate DateType="Electronic">
                <Year>2012</Year>
                <Month>11</Month>
                <Day>29</Day>
            </ArticleDate>
        </Article>
        <MedlineJournalInfo>
            <MedlineTA>Cephalalgia</MedlineTA>
            <NlmUniqueID>8200710</NlmUniqueID>
            <ISSNLinking>0333-1024</ISSNLinking>
        </MedlineJournalInfo>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>aheadofprint</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">0333102412470217</ArticleId>
            <ArticleId IdType="doi">10.1177/0333102412470217</ArticleId>
            <ArticleId IdType="pubmed">23197350</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Status="Publisher" Owner="NLM">
        <PMID Version="1">23197349</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print-Electronic">
            <Journal>
                <ISSN IssnType="Electronic">1468-2982</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <PubDate>
                        <Year>2012</Year>
                        <Month>Nov</Month>
                        <Day>29</Day>
                    </PubDate>
                </JournalIssue>
                <Title>Cephalalgia : an international journal of headache</Title>
                <ISOAbbreviation>Cephalalgia</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Use of cannabis among 139 cluster headache sufferers.</ArticleTitle>
            <Pagination>
                <MedlinePgn/>
            </Pagination>
            <Abstract>
                <AbstractText>Aims:A case report suggested the efficacy of cannabis to treat cluster headache (CH) attacks. Our aims were to study the frequency of cannabis use in CH patients, and the reported effects on attacks.Methods:A total of 139 patients with CH attending two French headache centers filled out questionnaires.Results:Sixty-three of the 139 patients (45.3%) had a history of cannabis use. As compared to nonusers, cannabis users were more likely to be younger, male and tobacco smokers. Among the 27 patients (19.4% of the total cohort) who had tried cannabis to treat CH attacks, 25.9% reported some efficacy, 51.8% variable or uncertain effects, and 22.3% negative effects.Conclusions:Cannabis use is very frequent in CH patients, but its efficacy for the treatment of the attacks is limited. Less than one third of self-reported users mention a relief of their attacks following inhalation. Cannabis should not be recommended for CH unless controlled trials with synthetic selective cannabinoids show a more convincing therapeutic benefit.</AbstractText>
            </Abstract>
            <Affiliation>Emergency Headache Center, Head and Neck Clinic, Hopital Lariboisiere, Assistance Publique des Hopitaux de Paris, France.</Affiliation>
            <AuthorList>
                <Author>
                    <LastName>Leroux</LastName>
                    <ForeName>Elizabeth</ForeName>
                    <Initials>E</Initials>
                </Author>
                <Author>
                    <LastName>Taifas</LastName>
                    <ForeName>Irina</ForeName>
                    <Initials>I</Initials>
                </Author>
                <Author>
                    <LastName>Valade</LastName>
                    <ForeName>Dominique</ForeName>
                    <Initials>D</Initials>
                </Author>
                <Author>
                    <LastName>Donnet</LastName>
                    <ForeName>Anne</ForeName>
                    <Initials>A</Initials>
                </Author>
                <Author>
                    <LastName>Chagnon</LastName>
                    <ForeName>Miguel</ForeName>
                    <Initials>M</Initials>
                </Author>
                <Author>
                    <LastName>Ducros</LastName>
                    <ForeName>Anne</ForeName>
                    <Initials>A</Initials>
                </Author>
            </AuthorList>
            <Language>ENG</Language>
            <PublicationTypeList>
                <PublicationType>JOURNAL ARTICLE</PublicationType>
            </PublicationTypeList>
            <ArticleDate DateType="Electronic">
                <Year>2012</Year>
                <Month>11</Month>
                <Day>29</Day>
            </ArticleDate>
        </Article>
        <MedlineJournalInfo>
            <MedlineTA>Cephalalgia</MedlineTA>
            <NlmUniqueID>8200710</NlmUniqueID>
            <ISSNLinking>0333-1024</ISSNLinking>
        </MedlineJournalInfo>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>aheadofprint</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">0333102412468669</ArticleId>
            <ArticleId IdType="doi">10.1177/0333102412468669</ArticleId>
            <ArticleId IdType="pubmed">23197349</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Status="Publisher" Owner="NLM">
        <PMID Version="1">23197348</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print-Electronic">
            <Journal>
                <ISSN IssnType="Electronic">1468-2982</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <PubDate>
                        <Year>2012</Year>
                        <Month>Nov</Month>
                        <Day>29</Day>
                    </PubDate>
                </JournalIssue>
                <Title>Cephalalgia : an international journal of headache</Title>
                <ISOAbbreviation>Cephalalgia</ISOAbbreviation>
            </Journal>
            <ArticleTitle>SUNCT, SUNA and pituitary tumors: Clinical characteristics and treatment.</ArticleTitle>
            <Pagination>
                <MedlinePgn/>
            </Pagination>
            <Abstract>
                <AbstractText>Background:Short-lasting unilateral neuralgiform headache attacks with conjunctival injection and tearing (SUNCT) and short-lasting unilateral neuralgiform headache attacks with cranial autonomic symptoms (SUNA) are rare types of trigeminal autonomic cephalalgias (TACs).Objective:To describe a series of patients with SUNCT and SUNA including relationship to pituitary tumors.Method:All patients diagnosed with SUNCT or SUNA in the Calgary Headache Assessment and Management Program were reviewed.Results:Six patients (five SUNCTs and one SUNA) were identified. The pain was severe, sharp, showed fixed-laterality, involved mainly the orbito-fronto-temporal region and was associated with autonomic symptoms. Attack duration ranged from 3 to 300 seconds and frequency was 1-200 paroxysms/day. MRI showed ipsilateral pituitary adenomas to the pain in five out of five of the SUNCT patients. Patients with adenomas underwent surgery. Pathology included three prolactinomas, and one mixed adenoma and gangliocytoma. One patient has remained headache free for 4 years after surgery. One was pain free for a year, and then headaches returned with tumor recurrence. Another had major improvement, and two have not improved. Patients were generally refractory to medications.Conclusion:All five of our patients with typical SUNCT had pituitary tumors, with headache ipsilateral to the pituitary tumors in all cases. Tumor removal provided major improvement in three out of five patients. Medical treatment was only partially effective.</AbstractText>
            </Abstract>
            <Affiliation>Department of Clinical Neurosciences, University of Calgary and Alberta Health Services, Canada.</Affiliation>
            <AuthorList>
                <Author>
                    <LastName>Chitsantikul</LastName>
                    <ForeName>Prin</ForeName>
                    <Initials>P</Initials>
                </Author>
                <Author>
                    <LastName>Becker</LastName>
                    <ForeName>Werner J</ForeName>
                    <Initials>WJ</Initials>
                </Author>
            </AuthorList>
            <Language>ENG</Language>
            <PublicationTypeList>
                <PublicationType>JOURNAL ARTICLE</PublicationType>
            </PublicationTypeList>
            <ArticleDate DateType="Electronic">
                <Year>2012</Year>
                <Month>11</Month>
                <Day>29</Day>
            </ArticleDate>
        </Article>
        <MedlineJournalInfo>
            <MedlineTA>Cephalalgia</MedlineTA>
            <NlmUniqueID>8200710</NlmUniqueID>
            <ISSNLinking>0333-1024</ISSNLinking>
        </MedlineJournalInfo>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>aheadofprint</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">0333102412468672</ArticleId>
            <ArticleId IdType="doi">10.1177/0333102412468672</ArticleId>
            <ArticleId IdType="pubmed">23197348</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Owner="NLM" Status="In-Data-Review">
        <PMID Version="1">23196737</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print">
            <Journal>
                <ISSN IssnType="Print">1028-768X</ISSN>
                <JournalIssue CitedMedium="Print">
                    <Volume>21</Volume>
                    <Issue>3</Issue>
                    <PubDate>
                        <Year>2012</Year>
                        <Month>Sep</Month>
                    </PubDate>
                </JournalIssue>
                <Title>Acta neurologica Taiwanica</Title>
                <ISOAbbreviation>Acta Neurol Taiwan</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Sentinel headache: a prospective case.</ArticleTitle>
            <Pagination>
                <MedlinePgn>147-8</MedlinePgn>
            </Pagination>
            <Affiliation>Department of Medicine National Yang-Ming University, Taipei, Taiwan.</Affiliation>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Cheng</LastName>
                    <ForeName>Yu-Chen</ForeName>
                    <Initials>YC</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Wong</LastName>
                    <ForeName>Yin-Kin</ForeName>
                    <Initials>YK</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Lai</LastName>
                    <ForeName>Tzu-Hsien</ForeName>
                    <Initials>TH</Initials>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType>Journal Article</PublicationType>
            </PublicationTypeList>
        </Article>
        <MedlineJournalInfo>
            <Country>China (Republic : 1949- )</Country>
            <MedlineTA>Acta Neurol Taiwan</MedlineTA>
            <NlmUniqueID>9815355</NlmUniqueID>
            <ISSNLinking>1028-768X</ISSNLinking>
        </MedlineJournalInfo>
        <CitationSubset>IM</CitationSubset>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>ppublish</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">10196099/213147</ArticleId>
            <ArticleId IdType="pubmed">23196737</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Owner="NLM" Status="In-Data-Review">
        <PMID Version="1">23196598</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print">
            <Journal>
                <ISSN IssnType="Electronic">1882-0654</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <Volume>52</Volume>
                    <Issue>11</Issue>
                    <PubDate>
                        <Year>2012</Year>
                    </PubDate>
                </JournalIssue>
                <Title>Rinsho shinkeigaku = Clinical neurology</Title>
                <ISOAbbreviation>Rinsho Shinkeigaku</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Application of acupuncture as a headache management tool.</ArticleTitle>
            <Pagination>
                <MedlinePgn>1299-302</MedlinePgn>
            </Pagination>
            <Abstract>
                <AbstractText>We use two oriental medical techniques in headache management. One is topological microstimulation, and the other is acupuncture point BL10 (Tianzhu) block. 1. Topological microstimulation The topological microstimulation apparatus delivers programmed fluctuating electrical signals to electrodes placed on the distal portion of the limbs, where meridians are concentrated. Topological microstimulation adjusts &quot;qi-blood-fluid&quot; circulating through meridians. &quot;Qi-blood-fluid&quot; is a virtual concept of oriental medicine that means 3 elements (qi, blood, and colorless body fluid). Topological microstimulation induces natural healing power through the bio-homeostatic function, and reduces chronic intractable pain. 2. Acupuncture point BL10 (Tianzhu) block Tianzhu as a meridian point is located at the intersection of the superior nuchal line of the occipital bone and lateral border of the trapezius. This site is located in the superficial layer of the trunk of the greater occipital nerve. Tianzhu block has therapeutic effects on the trigeminocervical complex. As a result, various types of headache are relieved. Tianzhu block was performed in 50 patients in our clinic, and marked effects were observed in 6 patients, moderate effects in 22, slight effects in 19, and no effects in 3. According to the type of headache, this block was effective in 47% of patients with tension-type headache, 38% of those with migraine, 50% of those with chronic daily headache, and 71% of those with neck and/or shoulder pain. Conclusion Various somatic and mental stresses induce headache and functional somatic syndrome, i.e., Tianzhu syndrome. Acupuncture is useful and can be actively recommended for the management of intractable headache such as complicated headache due to Tianzhu syndrome.</AbstractText>
            </Abstract>
            <Affiliation>Manaka Hospital.</Affiliation>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Manaka</LastName>
                    <ForeName>Sninya</ForeName>
                    <Initials>S</Initials>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType>Journal Article</PublicationType>
            </PublicationTypeList>
        </Article>
        <MedlineJournalInfo>
            <Country>Japan</Country>
            <MedlineTA>Rinsho Shinkeigaku</MedlineTA>
            <NlmUniqueID>0417466</NlmUniqueID>
            <ISSNLinking>0009-918X</ISSNLinking>
        </MedlineJournalInfo>
        <CitationSubset>IM</CitationSubset>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>ppublish</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">DN/JST.JSTAGE/clinicalneurol/52.1299</ArticleId>
            <ArticleId IdType="pubmed">23196598</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Owner="NLM" Status="In-Data-Review">
        <PMID Version="1">23196597</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print">
            <Journal>
                <ISSN IssnType="Electronic">1882-0654</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <Volume>52</Volume>
                    <Issue>11</Issue>
                    <PubDate>
                        <Year>2012</Year>
                    </PubDate>
                </JournalIssue>
                <Title>Rinsho shinkeigaku = Clinical neurology</Title>
                <ISOAbbreviation>Rinsho Shinkeigaku</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Acupuncture; as a valuable tool for headache.</ArticleTitle>
            <Pagination>
                <MedlinePgn>1297-8</MedlinePgn>
            </Pagination>
            <Abstract>
                <AbstractText>Acupuncture is known as the effective tool for headache, but the mechanism of the effect is unknown. We already revealed the acupuncture effect in the clinical team of headache center in Keio University Hospital. Therefore, we tried to establish the animal model for elucidation of mechanism of acupuncture effect in the pathophysiology of headache. Resent study, we reveal the threshold-reduction of the genesis of the cortical spreading depression (CSD; thought as the trigger of migraine attack) during the trigeminal nerve stimulation. This result suggests that, the somatosensory stimulation may influence the occurrence and severity of the pathogenesis of migraine. Furthermore, we assume that our result may lead to the underlying mechanism of acupuncture effect.</AbstractText>
            </Abstract>
            <Affiliation>Department of Neurology, School of Medicine, Keio University.</Affiliation>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Toriumi</LastName>
                    <ForeName>Haruki</ForeName>
                    <Initials>H</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Ebine</LastName>
                    <ForeName>Taeko</ForeName>
                    <Initials>T</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Kuroi</LastName>
                    <ForeName>Toshiya</ForeName>
                    <Initials>T</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Mamoru</LastName>
                    <ForeName>Shibata</ForeName>
                    <Initials>S</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Shimizu</LastName>
                    <ForeName>Toshihiko</ForeName>
                    <Initials>T</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Suzuki</LastName>
                    <ForeName>Norihiro</ForeName>
                    <Initials>N</Initials>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType>Journal Article</PublicationType>
            </PublicationTypeList>
        </Article>
        <MedlineJournalInfo>
            <Country>Japan</Country>
            <MedlineTA>Rinsho Shinkeigaku</MedlineTA>
            <NlmUniqueID>0417466</NlmUniqueID>
            <ISSNLinking>0009-918X</ISSNLinking>
        </MedlineJournalInfo>
        <CitationSubset>IM</CitationSubset>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>ppublish</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">DN/JST.JSTAGE/clinicalneurol/52.1297</ArticleId>
            <ArticleId IdType="pubmed">23196597</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Owner="NLM" Status="In-Data-Review">
        <PMID Version="1">23196594</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print">
            <Journal>
                <ISSN IssnType="Electronic">1882-0654</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <Volume>52</Volume>
                    <Issue>11</Issue>
                    <PubDate>
                        <Year>2012</Year>
                    </PubDate>
                </JournalIssue>
                <Title>Rinsho shinkeigaku = Clinical neurology</Title>
                <ISOAbbreviation>Rinsho Shinkeigaku</ISOAbbreviation>
            </Journal>
            <ArticleTitle>The practical use of acupuncture and moxibustion treatment cooperated with neurological practice.</ArticleTitle>
            <Pagination>
                <MedlinePgn>1287-9</MedlinePgn>
            </Pagination>
            <Abstract>
                <AbstractText>The greatest number of patients in our department are those referred from the Department of Neurology. These patients usually present symptoms or conditions such as peripheral facial paralysis, primary headache, or cerebrovascular disorders; acupuncture and moxibustion treatment have resulted in an overall favorable effect. Regarding the effect of acupuncture and moxibustion treatment on the prevention of migraine attacks, a two-month course of acupuncture has been shown to decrease the number of days with a slight or moderate headache. Furthermore, we have seen a relation between the alleviation of headache and that of muscular tenderness in the neck-shoulder region and masticatory muscles. The results of Arterial Spin-Labeling MRI, by which we determine changes in cerebral blood flow before and after acupuncture stimulation in patients with migraine, have revealed that acupuncture stimulation induces an increase of blood flow in the thalamus and hypothalamus, opercular part, cingulate gyrus, and islet. This differs from the response obtained in healthy individuals. It has been shown that acupuncture and moxibustion for tension headache is highly effective and the action mechanism of acupuncture and moxibustion is associated with relaxation of masticatory muscles hypertonicity in the neck-shoulder region and normalization of circulation dynamics, contributing thereby to the alleviation of headache. Moreover, the automatic nervous system has been found to be related to such analgesic mechanism. Based on our experience, we consider that traditional medicine based on acupuncture and moxibustion is highly effective in patients with neurological symptoms.</AbstractText>
            </Abstract>
            <Affiliation>The Center for Oriental and Integrative Medicine, Saitama Medical University.</Affiliation>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Yamaguchi</LastName>
                    <ForeName>Satoru</ForeName>
                    <Initials>S</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Araki</LastName>
                    <ForeName>Nobuo</ForeName>
                    <Initials>N</Initials>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType>Journal Article</PublicationType>
            </PublicationTypeList>
        </Article>
        <MedlineJournalInfo>
            <Country>Japan</Country>
            <MedlineTA>Rinsho Shinkeigaku</MedlineTA>
            <NlmUniqueID>0417466</NlmUniqueID>
            <ISSNLinking>0009-918X</ISSNLinking>
        </MedlineJournalInfo>
        <CitationSubset>IM</CitationSubset>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>ppublish</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">DN/JST.JSTAGE/clinicalneurol/52.1287</ArticleId>
            <ArticleId IdType="pubmed">23196594</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Owner="NLM" Status="In-Data-Review">
        <PMID Version="1">23196501</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print">
            <Journal>
                <ISSN IssnType="Electronic">1882-0654</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <Volume>52</Volume>
                    <Issue>11</Issue>
                    <PubDate>
                        <Year>2012</Year>
                    </PubDate>
                </JournalIssue>
                <Title>Rinsho shinkeigaku = Clinical neurology</Title>
                <ISOAbbreviation>Rinsho Shinkeigaku</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Identification of biomarkers associated with migraine.</ArticleTitle>
            <Pagination>
                <MedlinePgn>1014-7</MedlinePgn>
            </Pagination>
            <Abstract>
                <AbstractText>The diagnosis of migraine can be difficult, even for headache specialists, because some patients do not necessarily fulfill the International Headache Society criteria for migraine. Hence, reliable disease markers of migraine are required for accurate migraine diagnosis. We performed &quot;Omics&quot; analysis such as transcriptomics, proteomics, and genomics utilizing the lymphoblast cell lines and serum obtained from migraineurs. We verified that afodrin, which was among the identified 15 genes that were differentially expressed in lymphoblasts originating from patients with migraine, increased after cortical spreading depression in an animal model. We also investigated the alterations of protein expressions induced by migraine attacks using proteomics analysis. Notably, in two migraineurs, the level of apolipoprotein E protein expression during attacks was significantly higher than pre-attack levels. Recently, we have found a novel family lineage with migraine. They also exhibit severe myalgia with arms and legs. GC binding protein which binds to vitamin D was identified as the product of the causative gene in this family. Our omics approach will contribute to a better understanding of migraine pathophysiology.</AbstractText>
            </Abstract>
            <Affiliation>Department of Neurology, Tokai University School of Medicine.</Affiliation>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Nagata</LastName>
                    <ForeName>Eiichiro</ForeName>
                    <Initials>E</Initials>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType>Journal Article</PublicationType>
            </PublicationTypeList>
        </Article>
        <MedlineJournalInfo>
            <Country>Japan</Country>
            <MedlineTA>Rinsho Shinkeigaku</MedlineTA>
            <NlmUniqueID>0417466</NlmUniqueID>
            <ISSNLinking>0009-918X</ISSNLinking>
        </MedlineJournalInfo>
        <CitationSubset>IM</CitationSubset>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>ppublish</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">DN/JST.JSTAGE/clinicalneurol/52.1014</ArticleId>
            <ArticleId IdType="pubmed">23196501</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>


<PubmedArticle>
    <MedlineCitation Owner="NLM" Status="In-Data-Review">
        <PMID Version="1">23196498</PMID>
        <DateCreated>
            <Year>2012</Year>
            <Month>11</Month>
            <Day>30</Day>
        </DateCreated>
        <Article PubModel="Print">
            <Journal>
                <ISSN IssnType="Electronic">1882-0654</ISSN>
                <JournalIssue CitedMedium="Internet">
                    <Volume>52</Volume>
                    <Issue>11</Issue>
                    <PubDate>
                        <Year>2012</Year>
                    </PubDate>
                </JournalIssue>
                <Title>Rinsho shinkeigaku = Clinical neurology</Title>
                <ISOAbbreviation>Rinsho Shinkeigaku</ISOAbbreviation>
            </Journal>
            <ArticleTitle>Cortical spreading depression and molecular genetics in migraine.</ArticleTitle>
            <Pagination>
                <MedlinePgn>1006-8</MedlinePgn>
            </Pagination>
            <Abstract>
                <AbstractText>Cortical spreading depression (CSD) is a slowly propagated wave of depolarization of neurons and glial cells, followed by a subsequent sustained suppression of spontaneous neuronal activity. Functional imaging studies of migraine patients have shown dramatic changes in blood flow and brain activity whose characteristics are similar to those of CSD, implicated in migraine visual aura. Although the trigeminal nerve innervates the meninges and participates in the genesis of migraine headaches, triggering mechanisms remain controversial and poorly understood. It is demonstrated by animal models that CSD activates trigeminovascular afferents and evokes a series of cortical meningeal and brainstem events consistent with the development of headache. Three familial hemiplegic migraine, a rare monogenic subtype of migraine with aura, genes have been identified, which all encode ion transporters, suggesting that disturbances in ion and neurotransmitter balances in the brain are responsible for this migraine type. Additional molecular insight into the pathophysiology of migraine may come from other monogenic syndromes such as CADASIL, RVCL. Several genetic associations with candidate migraine genes like ESR1, MTHFR, and INSR, have been convincingly replicated. The genome-wide association studies may be a successful strategy toward identification of migraine susceptibility genes.</AbstractText>
            </Abstract>
            <Affiliation>Division of Neurology, Department of Brain and Neurological Sciences, Faculty of Medicine, Tottori University.</Affiliation>
            <AuthorList CompleteYN="Y">
                <Author ValidYN="Y">
                    <LastName>Kowa</LastName>
                    <ForeName>Hisanori</ForeName>
                    <Initials>H</Initials>
                </Author>
                <Author ValidYN="Y">
                    <LastName>Nakashima</LastName>
                    <ForeName>Kenji</ForeName>
                    <Initials>K</Initials>
                </Author>
            </AuthorList>
            <Language>eng</Language>
            <PublicationTypeList>
                <PublicationType>Journal Article</PublicationType>
            </PublicationTypeList>
        </Article>
        <MedlineJournalInfo>
            <Country>Japan</Country>
            <MedlineTA>Rinsho Shinkeigaku</MedlineTA>
            <NlmUniqueID>0417466</NlmUniqueID>
            <ISSNLinking>0009-918X</ISSNLinking>
        </MedlineJournalInfo>
        <CitationSubset>IM</CitationSubset>
    </MedlineCitation>
    <PubmedData>
        <History>
            <PubMedPubDate PubStatus="entrez">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="pubmed">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
            <PubMedPubDate PubStatus="medline">
                <Year>2012</Year>
                <Month>12</Month>
                <Day>1</Day>
                <Hour>6</Hour>
                <Minute>0</Minute>
            </PubMedPubDate>
        </History>
        <PublicationStatus>ppublish</PublicationStatus>
        <ArticleIdList>
            <ArticleId IdType="pii">DN/JST.JSTAGE/clinicalneurol/52.1006</ArticleId>
            <ArticleId IdType="pubmed">23196498</ArticleId>
        </ArticleIdList>
    </PubmedData>
</PubmedArticle>

</PubmedArticleSet>

})

  FakeWeb.register_uri(:any, %r[http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch*], 
    :body => %Q{
<?xml version="1.0" ?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD eSearchResult, 11 May 2002//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/eSearch_020511.dtd">
<eSearchResult><Count>58413</Count><RetMax>100</RetMax><RetStart>0</RetStart><IdList>
		<Id>23197953</Id>
		<Id>23197746</Id>
		<Id>23197350</Id>
		<Id>23197349</Id>
		<Id>23197348</Id>
		<Id>23196737</Id>
		<Id>23196598</Id>
		<Id>23196597</Id>
		<Id>23196594</Id>
		<Id>23196501</Id>
		<Id>23196498</Id>
		<Id>23196488</Id>
		<Id>23196487</Id>
		<Id>23196446</Id>
		<Id>23196352</Id>
		<Id>23194278</Id>
		<Id>23194159</Id>
		<Id>23194101</Id>
		<Id>23193986</Id>
		<Id>23193633</Id>
		<Id>23192413</Id>
		<Id>23192335</Id>
		<Id>23190440</Id>
		<Id>23188975</Id>
		<Id>23188841</Id>
		<Id>23188123</Id>
		<Id>23187986</Id>
		<Id>23187300</Id>
		<Id>23185541</Id>
		<Id>23185256</Id>
		<Id>23185092</Id>
		<Id>23184667</Id>
		<Id>23184666</Id>
		<Id>23184269</Id>
		<Id>23183994</Id>
		<Id>23183526</Id>
		<Id>23183081</Id>
		<Id>23182737</Id>
		<Id>23182623</Id>
		<Id>23182175</Id>
		<Id>23181257</Id>
		<Id>23181051</Id>
		<Id>23180468</Id>
		<Id>23180057</Id>
		<Id>23179962</Id>
		<Id>23179682</Id>
		<Id>23179642</Id>
		<Id>23179186</Id>
		<Id>23177505</Id>
		<Id>23177380</Id>
		<Id>23176349</Id>
		<Id>23176335</Id>
		<Id>23163546</Id>
		<Id>23163545</Id>
		<Id>23163544</Id>
		<Id>23163543</Id>
		<Id>23175211</Id>
		<Id>23175005</Id>
		<Id>23174746</Id>
		<Id>23174659</Id>
		<Id>23172998</Id>
		<Id>23172516</Id>
		<Id>23172430</Id>
		<Id>23171751</Id>
		<Id>23171703</Id>
		<Id>23171565</Id>
		<Id>23171280</Id>
		<Id>23170308</Id>
		<Id>23170017</Id>
		<Id>23168979</Id>
		<Id>23168395</Id>
		<Id>23168249</Id>
		<Id>23168071</Id>
		<Id>23166578</Id>
		<Id>23166450</Id>
		<Id>23166446</Id>
		<Id>23166204</Id>
		<Id>23165696</Id>
		<Id>23165695</Id>
		<Id>23165338</Id>
		<Id>23165010</Id>
		<Id>23164653</Id>
		<Id>23163838</Id>
		<Id>23163496</Id>
		<Id>23163207</Id>
		<Id>23153206</Id>
		<Id>23162198</Id>
		<Id>23162193</Id>
		<Id>23162044</Id>
		<Id>23161120</Id>
		<Id>23161035</Id>
		<Id>23160810</Id>
		<Id>23160686</Id>
		<Id>23160230</Id>
		<Id>23160227</Id>
		<Id>23160225</Id>
		<Id>23160091</Id>
		<Id>23159967</Id>
		<Id>23159646</Id>
		<Id>23159522</Id>
	</IdList><TranslationSet><Translation>     <From>headache</From>     <To>"headache"[MeSH Terms] OR "headache"[All Fields]</To>    </Translation></TranslationSet><TranslationStack>   <TermSet>    <Term>"headache"[MeSH Terms]</Term>    <Field>MeSH Terms</Field>    <Count>21053</Count>    <Explode>Y</Explode>   </TermSet>   <TermSet>    <Term>"headache"[All Fields]</Term>    <Field>All Fields</Field>    <Count>58409</Count>    <Explode>Y</Explode>   </TermSet>   <OP>OR</OP>   <OP>GROUP</OP>  </TranslationStack><QueryTranslation>"headache"[MeSH Terms] OR "headache"[All Fields]</QueryTranslation></eSearchResult>

    }  )

  visit path_to(page_name)
end

When /^(?:|I )go to (.+)$/ do |page_name|
  visit path_to(page_name)
end

When /^(?:|I )press "([^"]*)"$/ do |button|
  click_button(button)
end

When /^(?:|I )follow "([^"]*)"$/ do |link|
  click_link(link)
end

When /^(?:|I )fill in "([^"]*)" with "([^"]*)"$/ do |field, value|
  fill_in(field, :with => value)
end

When /^(?:|I )fill in "([^"]*)" for "([^"]*)"$/ do |value, field|
  fill_in(field, :with => value)
end

# Use this to fill in an entire form with data from a table. Example:
#
#   When I fill in the following:
#     | Account Number | 5002       |
#     | Expiry date    | 2009-11-01 |
#     | Note           | Nice guy   |
#     | Wants Email?   |            |
#
# TODO: Add support for checkbox, select or option
# based on naming conventions.
#
When /^(?:|I )fill in the following:$/ do |fields|
  fields.rows_hash.each do |name, value|
    When %{I fill in "#{name}" with "#{value}"}
  end
end

When /^(?:|I )select "([^"]*)" from "([^"]*)"$/ do |value, field|
  select(value, :from => field)
end

When /^(?:|I )check "([^"]*)"$/ do |field|
  check(field)
end

When /^(?:|I )uncheck "([^"]*)"$/ do |field|
  uncheck(field)
end

When /^(?:|I )choose "([^"]*)"$/ do |field|
  choose(field)
end

When /^(?:|I )attach the file "([^"]*)" to "([^"]*)"$/ do |path, field|
  attach_file(field, File.expand_path(path))
end

Then /^(?:|I )should see "([^"]*)"$/ do |text|
  if page.respond_to? :should
    page.should have_content(text)
  else
    assert page.has_content?(text)
  end
end

Then /^(?:|I )should see \/([^\/]*)\/$/ do |regexp|
  regexp = Regexp.new(regexp)

  if page.respond_to? :should
    page.should have_xpath('//*', :text => regexp)
  else
    assert page.has_xpath?('//*', :text => regexp)
  end
end

Then /^(?:|I )should not see "([^"]*)"$/ do |text|
  if page.respond_to? :should
    page.should have_no_content(text)
  else
    assert page.has_no_content?(text)
  end
end

Then /^(?:|I )should not see \/([^\/]*)\/$/ do |regexp|
  regexp = Regexp.new(regexp)

  if page.respond_to? :should
    page.should have_no_xpath('//*', :text => regexp)
  else
    assert page.has_no_xpath?('//*', :text => regexp)
  end
end

Then /^the "([^"]*)" field(?: within (.*))? should contain "([^"]*)"$/ do |field, parent, value|
  with_scope(parent) do
    field = find_field(field)
    field_value = (field.tag_name == 'textarea') ? field.text : field.value
    if field_value.respond_to? :should
      field_value.should =~ /#{value}/
    else
      assert_match(/#{value}/, field_value)
    end
  end
end

Then /^the "([^"]*)" field(?: within (.*))? should not contain "([^"]*)"$/ do |field, parent, value|
  with_scope(parent) do
    field = find_field(field)
    field_value = (field.tag_name == 'textarea') ? field.text : field.value
    if field_value.respond_to? :should_not
      field_value.should_not =~ /#{value}/
    else
      assert_no_match(/#{value}/, field_value)
    end
  end
end

Then /^the "([^"]*)" field should have the error "([^"]*)"$/ do |field, error_message|
  element = find_field(field)
  classes = element.find(:xpath, '..')[:class].split(' ')

  form_for_input = element.find(:xpath, 'ancestor::form[1]')
  using_formtastic = form_for_input[:class].include?('formtastic')
  error_class = using_formtastic ? 'error' : 'field_with_errors'

  if classes.respond_to? :should
    classes.should include(error_class)
  else
    assert classes.include?(error_class)
  end

  if page.respond_to?(:should)
    if using_formtastic
      error_paragraph = element.find(:xpath, '../*[@class="inline-errors"][1]')
      error_paragraph.should have_content(error_message)
    else
      page.should have_content("#{field.titlecase} #{error_message}")
    end
  else
    if using_formtastic
      error_paragraph = element.find(:xpath, '../*[@class="inline-errors"][1]')
      assert error_paragraph.has_content?(error_message)
    else
      assert page.has_content?("#{field.titlecase} #{error_message}")
    end
  end
end

Then /^the "([^"]*)" field should have no error$/ do |field|
  element = find_field(field)
  classes = element.find(:xpath, '..')[:class].split(' ')
  if classes.respond_to? :should
    classes.should_not include('field_with_errors')
    classes.should_not include('error')
  else
    assert !classes.include?('field_with_errors')
    assert !classes.include?('error')
  end
end

Then /^the "([^"]*)" checkbox(?: within (.*))? should be checked$/ do |label, parent|
  with_scope(parent) do
    field_checked = find_field(label)['checked']
    if field_checked.respond_to? :should
      field_checked.should be_true
    else
      assert field_checked
    end
  end
end

Then /^the "([^"]*)" checkbox(?: within (.*))? should not be checked$/ do |label, parent|
  with_scope(parent) do
    field_checked = find_field(label)['checked']
    if field_checked.respond_to? :should
      field_checked.should be_false
    else
      assert !field_checked
    end
  end
end
 
Then /^(?:|I )should be on (.+)$/ do |page_name|
  current_path = URI.parse(current_url).path
  if current_path.respond_to? :should
    current_path.should == path_to(page_name)
  else
    assert_equal path_to(page_name), current_path
  end
end

Then /^(?:|I )should have the following query string:$/ do |expected_pairs|
  query = URI.parse(current_url).query
  actual_params = query ? CGI.parse(query) : {}
  expected_params = {}
  expected_pairs.rows_hash.each_pair{|k,v| expected_params[k] = v.split(',')} 
  
  if actual_params.respond_to? :should
    actual_params.should == expected_params
  else
    assert_equal expected_params, actual_params
  end
end

Then /^show me the page$/ do
  save_and_open_page
end
